DROP TABLE IF EXISTS links CASCADE;

--

CREATE TABLE IF NOT EXISTS links (
id INT AUTO_INCREMENT NOT NULL,
original TEXT NOT NULL,
short VARCHAR(5) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;
