DROP TABLE IF EXISTS links CASCADE;

CREATE TABLE IF NOT EXISTS links (
id INT AUTO_INCREMENT NOT NULL,
original VARCHAR(1024) UNIQUE NOT NULL,
short VARCHAR(7) UNIQUE NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=UTF8;